### ISSUE TITLE
feat: add a healthcheck in docker compose

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot-rpc#337]
# Feature Request

**Describe the Feature Request**

When using the docker compose file as is

```
docker compose up
```

then the `deployer` first throws some errors because madara is not ready

**Describe Preferred Solution**

Add a `healthcheck` section in the compose file, like (not tested)

```
    healthcheck:
      test: curl --fail http://0.0.0.0:9944  -H 'content-type: application/json'  --data-raw '{"method":"starknet_chainId","jsonrpc":"2.0","params":[],"id":0}' || exit 1
      interval: 2s
      retries: 5
      timeout: 2s
```
