### ISSUE TITLE
feat: add a docker compose to run kakarot sepolia stack 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#810]
currently only Karnot has a stack to interact with kakarot sepolia (and @Eikix locally)

```[tasklist]
### Tasks
- [ ] create a new docker compose that can run: Juno, kakarot RPC, Stark Compass, DNA indexer, indexer, mongodb and possibly blockscout
- [ ] ask @Eikix or @d-roak to run it on the kakanode (onlydesk rocks-5b)
``` 

# Suggestions: combine the below two docker compose (while deleting Katana, Parser and Deployer services), load parser env's with the Kakarot Sepolia deployment file
```yaml
version: '3.8'
services:
  madara-explorer:
    image: ghcr.io/lambdaclass/stark_compass_explorer:v0.2.37
    ports:
      - "4000:4000"
    environment:
      - PHX_HOST=localhost
      - PORT=4000
      - RPC_API_HOST=http://host.docker.internal:6060
      - TESTNET_RPC_API_HOST=http://host.docker.internal:6060
      - SEPOLIA_RPC_API_HOST=http://host.docker.internal:6060
      - DISABLE_MAINNET_SYNC=true
      - DISABLE_SEPOLIA_SYNC=true
      - DATABASE_PATH=ecto://postgres:postgres@madara-explorer-db:5432/starknet_explorer_dev
      - DB_TYPE=postgres
      - SECRET_KEY_BASE=JyULoT5cLBifW+XNEuCTVoAb+SaFgQt9j227RN0cKpR3wTsrApGd1HNcgeopemyl
      - ENABLE_LISTENER=true
    depends_on:
      madara-explorer-db:
        condition: service_started
      juno:
        condition: service_started
    extra_hosts:
      - host.docker.internal:172.17.0.1
  juno:
    image: nethermind/juno:v0.9.4
    ports:
        - 6060:6060
    volumes:
      - ./juno_files/:/var/lib/juno
    command: >
      --pending-poll-interval "10s"
      --http
      --http-host 0.0.0.0
      --http-port 6060
      --db-path /var/lib/juno
      --eth-node wss://eth-sepolia.g.alchemy.com/v2/WIUR5JUZXieEBkze6Xs3IOXWhsS840TX
      --cn-name kakarot-sepolia
      --cn-feeder-url https://gateway.kakarot.sw-dev.io/feeder_gateway/
      --cn-gateway-url https://gateway.kakarot.sw-dev.io/gateway/
      --cn-l1-chain-id 0xaa36a7
      --cn-l2-chain-id kkrt
      --cn-core-contract-address 0x9DAd05893305352cDd142F79e36bc39393F23770
      --cn-unverifiable-range 0,1000000

  madara-explorer-db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starknet_explorer_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.data/madara-explorer/:/var/lib/postgresql/data/

networks:
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  pgadmin_data:


```

```yaml
version: "3.2"

services:
  starknet:
    image: ghcr.io/dojoengine/dojo:v0.6.0-alpha.2
    command:
      - katana
      - --disable-fee
      - --validate-max-steps
      - "16777216"
      - --invoke-max-steps
      - "16777216"
      - --eth-gas-price
      - "0"
      - --strk-gas-price
      - "0"
      - --chain-id
      - "kkrt"
    ports:
      - "5050:5050"
    networks:
      - internal
    restart: on-failure

  kakarot-deployer:
    image: ghcr.io/kkrt-labs/kakarot/deployer:latest
    # Always pull the latest image, until we use release tags
    pull_policy: always
    environment:
      - ACCOUNT_ADDRESS=0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca
      - PRIVATE_KEY=0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a
      - EVM_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - RPC_URL=http://starknet:5050
    volumes:
      # Since STARKNET_NETWORK is not set, deployments will be saved without network folder
      - deployments:/app/kakarot/deployments
    depends_on:
      starknet:
        condition: service_started
    restart: on-failure
    networks:
      - internal

  deployments-parser:
    image: apteno/alpine-jq:2023-07-24
    # Parse deployments and save the result to .env file
    entrypoint:
      - "/bin/sh"
      - "-c"
      # First line overrides an existing .env, if any.
      # This is to make sure that it is clean even though docker volume was not cleaned.
      - |
        echo "KAKAROT_ADDRESS=$$(jq -r '.kakarot.address' /deployments/custom-rpc/deployments.json)" > /deployments/.env;
        echo "DEPLOYER_ACCOUNT_ADDRESS=$$(jq -r '.deployer_account.address' /deployments/custom-rpc/deployments.json)" >> /deployments/.env;
        echo "PROXY_ACCOUNT_CLASS_HASH=$$(jq -r '.proxy' /deployments/custom-rpc/declarations.json)" >> /deployments/.env
        echo "EXTERNALLY_OWNED_ACCOUNT_CLASS_HASH=$$(jq -r '.externally_owned_account' /deployments/custom-rpc/declarations.json)" >> /deployments/.env
        echo "CONTRACT_ACCOUNT_CLASS_HASH=$$(jq -r '.contract_account' /deployments/custom-rpc/declarations.json)" >> /deployments/.env
    volumes:
      - deployments:/deployments
    depends_on:
      kakarot-deployer:
        condition: service_completed_successfully

  kakarot-rpc:
    image: eliastazartes/kakarot-rpc:latest
    # Always pull the latest image, until we use release tags
    # TODO: use release tags
    pull_policy: always
    ports:
      - 3030:3030
    environment:
      - KAKAROT_RPC_URL=0.0.0.0:3030
      - STARKNET_NETWORK=http://starknet:5050
      - RUST_LOG=kakarot_rpc=info
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DATABASE_NAME=kakarot-local
    volumes:
      # Mount the volume on workdir and use .env stored in root of the volume
      - deployments:/usr/src/app
    depends_on:
      deployments-parser:
        condition: service_completed_successfully
    restart: on-failure
    networks:
      - internal

  apibara-dna:
    image: quay.io/apibara/starknet:1.4.0
    command:
      - start
      - --rpc=http://starknet:5050
      - --wait-for-rpc
      - --data=/data
    ports:
      - 7171:7171
    volumes:
      - apibara:/data
    networks:
      - internal
    restart: on-failure
    depends_on:
      kakarot-deployer:
        condition: service_completed_successfully
      starknet:
        condition: service_started

  ### MongoDB with Mongo Express
  mongo:
    image: mongo:6.0.8
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  clone-repo:
    image: docker.io/alpine/git:latest
    entrypoint: "/bin/sh"
    command:
      - "-c"
      # clone the repository in `/code`, removing any old copy.
      - "cd /code && rm -rf kakarot-indexer && git clone -v https://github.com/kkrt-labs/kakarot-indexer.git"
    volumes:
      - "indexer_code:/code"
    restart: on-failure

  indexer:
    image: quay.io/apibara/sink-mongo
    command:
      - run
      - /code/kakarot-indexer/src/main.ts
    environment:
      # Whitelist environment variables
      - ALLOW_ENV_FROM_ENV=DEBUG,APIBARA_AUTH_TOKEN,STARTING_BLOCK,STREAM_URL,SINK_TYPE,MONGO_CONNECTION_STRING,MONGO_DATABASE_NAME
      - DEBUG=""
      - APIBARA_AUTH_TOKEN=""
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DATABASE_NAME=kakarot-local
      - STARTING_BLOCK=0
      - STREAM_URL=http://apibara-dna:7171
      - SINK_TYPE=mongo
    restart: on-failure
    volumes:
      - "indexer_code:/code"
    networks:
      - internal
    depends_on:
      clone-repo:
        condition: service_completed_successfully
      starknet:
        condition: service_started
      kakarot-deployer:
        condition: service_completed_successfully

networks:
  internal:

volumes:
  deployments:
  apibara:
  mongo_data:
  indexer_code:
```

```
Deployment Kakarot Sepolia

kakarot class hash: 0x42827792b0b3ed1f906bc96e0fab366244aed74ea87db51e74d4a1b77ae1e7f

contract_account class hash: 0x34e8e05a28a6ac98118860ae0cca56487e2f0a3589a4b713a0f19ccda3386d9

externally_owned_account class hash: 0x2ab68b7f5cea86752714b499f602cdb8c36e8cdf270f04b6a275b609baf7aea

proxy class hash: 0x5bcd4d02cfe3aeb836f2ef4bd21b2020793e52a8269dbef9cd883fbddd2963c

OpenzeppelinAccount class hash: 0x452189b6cd1ef66a7daef29cbffb77ce809cac95449687aabb169117c04e2f9

Precompiles class hash: 0x4afd993d1327dcae9a307a91447b62537ca1f683ed78757f25cecc19e05b4de

kakarot deployed at: 0x1a18210c20241ea7a06224246264a59add11c8358d69826e8bd51f4ba6d3be7

— Account —
Account deployed at address 0x531befddbb36eb5632a96699ee83a1584e89d5405abc9bfbbf81ecc1f65679f

— Funding —
1.0 ETH sent from 0x43abaa073c768ebf039c0c4f46db9acc39e9ec165690418060a652aab39e7d8 to 0x203e7de57f863e59040918c8bd67cc03d6c3dd5db0f2bda49bac5f59073374


Funding EVM address 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 at Starknet address 0x6d97e52f4c3966dc66e1736a92671a5fa1abcc78e621fdb6163a1658cab5870
Addresses:
eth: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
sn: 0x6d97e52f4c3966dc66e1736a92671a5fa1abcc78e621fdb6163a1658cab5870


Fixtures:
EVM class hash: 0x7efd13e916e989f0bd6fcb7be607ca095099b5bbcaa0cd7b8c20e81ac1a2028
replace_class class hash: 0x5cd1a33bc766f50965fe2343e6aec12a12c562b3bb653085b88dc6751b71682
EVM deployed at: 0x5535633563d64727d8af818146a35ad76ff4bb32baf5221881c4e8e9f7ee8c5
```
